#commands and responses
commands = [
    'hello',
    'who are you',
    'what is a stock',
    'goodbye',
    'how do I buy stocks',
    'what is the stock market',
    'recommend a stock',
    'what are dividends',
    'how to read a stock chart',
    'what is a bear market',
    'what is a bull market',
    'explain market capitalization',
    'what is an etf',
    'how to diversify my portfolio',
    'what is risk tolerance',
    'how does inflation affect stocks',
    'what is a blue-chip stock',
    'explain stock splits',
    'what is a bond',
    'how to analyze a stock',
    'what is an ipo',
    'explain short selling',
    'what are growth stocks',
    'what is value investing',
    'explain mutual funds',
    'what is a portfolio',
    'what is a moving average',
    'explain simple moving average',
    'what is an exponential moving average',
    'define support level in stocks',
    'what is a resistance level',
    'explain bollinger bands',
    'what is the rsi indicator',
    'explain macd in stock trading',
    'what is a fibonacci retracement',
    'define candlestick patterns'
]

responses = [
    'Hello! How can I help you?',
    'I am a stock recommender chatbot!',
    'A stock is a share in the ownership of a company, including a claim on the company\'s earnings and assets',
    'See ya!',
    'To buy stocks, you need to open a brokerage account, fund it, and then you can start buying stocks through the platform.',
    'The stock market is a collection of markets where stocks (pieces of ownership in businesses) are bought and sold between investors.',
    'Try out our analyst by clicking "Go to Analysis Page" and entering a company or ticker to see it\'s current sentiment',
    'Dividends are a portion of a company\'s earnings that are paid out to shareholders on a regular basis.',
    'To read a stock chart, look at the X-axis for the time frame and the Y-axis for the price. Pay attention to patterns, trends, and key indicators like volume and moving averages.',
    'A bear market is a market condition where prices are falling or are expected to fall, typically by 20 percent or more from recent highs.',
    'A bull market is a market condition where prices are rising or are expected to rise. It\'s generally characterized by strong investor confidence.',
    'Market capitalization refers to the total market value of a company\'s outstanding shares. It\'s calculated by multiplying the current stock price by the total number of outstanding shares.',
    'An ETF, or Exchange-Traded Fund, is a type of investment fund that holds assets like stocks, bonds, or commodities, and is traded on stock exchanges, similar to stocks.',
    'To diversify your portfolio, invest in a variety of assets like stocks, bonds, and commodities across different industries and geographical regions to spread risk.',
    'Risk tolerance is the degree of variability in investment returns that an investor is willing to withstand in their investment portfolio.',
    'Inflation can affect stocks in various ways. Typically, moderate inflation is associated with economic growth, which can be good for stocks. However, high inflation can erode purchasing power and lead to higher interest rates, which may negatively impact stock prices.',
    'Blue-chip stocks are shares of large, well-established, and financially stable companies with a history of reliable growth and dividends.',
    'A stock split is when a company divides its existing shares into multiple new shares to boost the stock\'s liquidity. Although the number of shares outstanding increases, the total dollar value of the shares remains the same, making individual shares more affordable.',
    'A bond is a fixed-income instrument that represents a loan made by an investor to a borrower, typically corporate or governmental. Bonds are used by companies, municipalities, states, and sovereign governments to finance projects and operations.',
    'To analyze a stock, consider its financial health, management quality, industry position, market trends, and its price-to-earnings ratio among other factors. Also, look at the company\'s earnings reports, balance sheet, and future growth prospects.',
    'An IPO, or Initial Public Offering, is when a company first sells its shares to the public. This process allows a company to raise capital from public investors.',
    'Short selling is an investment strategy where an investor borrows shares and sells them on the open market, planning to buy them back later for less money. It\'s a way to profit from a stock\'s price decline.',
    'Growth stocks are shares in companies that are expected to grow at an above-average rate compared to other companies in the market. These stocks typically do not pay dividends and are more volatile.',
    'Value investing is an investment strategy where stocks are selected that appear to be trading for less than their intrinsic or book value. Investors believe the market has undervalued these stocks.',
    'A mutual fund is an investment vehicle made up of a pool of funds collected from many investors for the purpose of investing in securities such as stocks, bonds, money market instruments, and other assets.',
    'A portfolio is a collection of financial investments like stocks, bonds, commodities, cash, and cash equivalents, including closed-end funds and exchange traded funds (ETFs).',
    'A moving average is a statistical tool that smooths out price data by creating a constantly updated average price over a specific time period. It helps in identifying the direction of the trend and smoothing out price fluctuations.',
    'A Simple Moving Average (SMA) is a technical indicator that calculates the average of a selected range of prices, usually closing prices, by the number of periods in that range. It\'s a straightforward way of looking at the average price of a stock over a specific time frame.',
    'An Exponential Moving Average (EMA) is a type of moving average that places a greater weight and significance on the most recent data points. It reacts more significantly to recent price changes than a simple moving average (SMA), which applies an equal weight to all observations in the period.',
    'A support level in stock trading is a price level at which a stock tends to stop falling and may bounce back upward. It\'s where the demand is thought to be strong enough to prevent the price from declining further.',
    'A resistance level is the opposite of a support level. It\'s a price point at which a stock tends to stop rising and may start to decline. Resistance levels indicate where selling interest overcomes buying pressure and a price advance is turned back.',
    'Bollinger Bands are a technical analysis tool defined by a set of lines plotted two standard deviations (positively and negatively) away from a simple moving average (SMA) of a security\'s price, but can be adjusted to user preferences.',
    'The Relative Strength Index (RSI) is a momentum indicator used in technical analysis. It measures the magnitude of recent price changes to evaluate overbought or oversold conditions in the price of a stock or other asset.',
    'MACD, or Moving Average Convergence Divergence, is a trend-following momentum indicator that shows the relationship between two moving averages of a security\'s price. It is used to identify bullish or bearish momentum in the stock market.',
    'Fibonacci retracement is a technical analysis tool that uses horizontal lines to indicate areas of support or resistance at the key Fibonacci levels before the price continues in the original direction. These levels are based on Fibonacci numbers.',
    'Candlestick patterns are a method of technical analysis used in stock trading. It involves the interpretation of candlestick charts, which display the high, low, opening, and closing prices of a security for a specific period. These patterns help predict future price movements.'
]